---

- name: Accept vrrp
  ansible.posix.firewalld:
    rich_rule: rule protocol value="vrrp" accept
    zone: public
    permanent: true
    immediate: true
    state: enabled

- name: Update dnf/yum cache
  ansible.builtin.yum:
    update_cache: true
  when: ansible_pkg_mgr == 'dnf' or ansible_pkg_mgr == 'yum'

- name: Install packages
  ansible.builtin.package:
    name: keepalived

- name: Create directory for keepalived
  ansible.builtin.file:
    path: /etc/keepalived
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Create Kubernetes API health check script for RedHat OS famliy
  ansible.builtin.template:
    src: templates/check_apiserver.sh.j2
    dest: /usr/libexec/keepalived/check_apiserver.sh
    owner: root
    group: root
    mode: 0755
  when:  ansible_facts['os_family'] == "RedHat"
  notify: Restart keepalived

- name: Create keepalived config file
  ansible.builtin.template:
    src: templates/keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
    owner: root
    group: root
    mode: 0644
  notify: Restart keepalived

- name: Enable keepalived and make sure it is not masked
  ansible.builtin.systemd:
    name: keepalived
    enabled: yes
    masked: no
  notify: Restart keepalived

- name: Flush handlers
  ansible.builtin.meta: flush_handlers